name: Maven Build

on:
  push:
    branches: [ release* ]

jobs:
  build:
   runs-on: ubuntu-latest   
   env:
    JFROG_USER: ${{secrets.JFROG_USER}}
    JFROG_PASS: ${{secrets.JFROG_PASS}} 
    
   steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: jfrog
        server-username: JFROG_USER
        server-password: JFROG_PASS

    - name: Build with Maven
      run: mvn clean install
